version: "2"
virtualmachines:
- name: workstation
  image: instruqt-hashicorp/terraform-workstation
  shell: /bin/bash
  machine_type: n1-standard-1
  ports:
  - 8443
  - 5000
aws_accounts:
- name: TF-WORKSHOP
  managed_policies:
  - arn:aws:iam::aws:policy/AmazonEC2FullAccess
  - arn:aws:iam::aws:policy/AmazonVPCFullAccess
