version: "2"
containers:
- name: cloud-client
  image: gcr.io/instruqt-hashicorp/hashiworkstation:latest
  shell: /bin/bash
  ports:
  - 80
  environment:
    ARM_SUBSCRIPTION_ID: 14692f20-9428-451b-8298-102ed4e39c2a
    ARM_TENANT_ID: 0e3e2e88-8caf-41ca-b4da-e3b33b6c52ec
    VAULT_ADDR: https://cam-vault.hashidemos.io:8200
    VAULT_CREDS_ENDPOINT: azure/creds/se-training-workstation
    VAULT_NAMESPACE: Sales/SE
aws_accounts:
- name: aws
  managed_policies:
  - arn:aws:iam::aws:policy/IAMFullAccess
  - arn:aws:iam::aws:policy/AmazonEC2FullAccess
