version: "2"
virtualmachines:
- name: workstation
  image: instruqt-hashicorp/terraform-workstation-0-14-9
  shell: /bin/bash -l
  machine_type: n1-standard-1
azure_subscriptions:
- name: terraform
  roles:
  - Owner
